#!/bin/sh
mlt raw "{\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko {\r}\x1Bko"
#mlt raw 'a[0]); a[0]); a[0]); a[0]); a[0]); a[0]); a[0]); a[0]); a[0]); a[0]); a[0]); '
#mlt raw '[x]) { [x]) { [x]) { [x]) { [x]) { [x]) { [x]) { [x]) { [x]) { [x]) { [x]) { '
#mlt raw '= [&] ( x) -> int { = [&] ( x) -> int { = [&] ( x) -> int { = [&] ( x) -> int { = [&] ( x) -> int { = [&] ( x) -> int { = [&] ( x) -> int { = [&] ( x) -> int { = [&] ( x) -> int { = [&] ( x) -> int { = [&] ( x) -> int { '
# mlt raw " i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i);"

# mlt raw " i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i);"
#
# mlt raw '("%d \n"); ("%d \n"); ("%d \n"); ("%d \n"); ("%d \n"); ("%d \n"); ("%d \n"); ("%d \n"); ("%d \n"); ("%d \n"); ("%d \n"); '

#------选中函数
#------ r4] r3[ <leftshift>v l3% l2y r3d -------选中函数yd
# mlt raw ";jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky "

# mlt raw "for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko for (int i = 0; i < 100; ++i) {\r}\x1Bko {\r}\x1Bko"
