<#
Original shell script convert to Powershell for Windows
Original tool: mlt
#>

# mlt random "1234567890-=!@#`$%^&*()_+qwertyuiop[]{}\|"
# scp ./ml.sh hoverzhao@192.168.1.102

##----- typing  cw ce vb cw ce vb cw ce vb
## l2c l4w l3e l2v r2b
# mlt raw " cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cwfww cwf cwf cwfw cwf cwf cwf cwf cwfw cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cwf cww cwf cwf cwfw cwf cwf cwf cwf cwfw"
# mlt raw " cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef cef"
# mlt raw " vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd vbd"
# mlt raw " ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved ved"

# ();
# {};
# "";
# (" ");
# = '';
# [] = "";
# int a[3] = {0, 1, 2};
# var o = {a: 'foo', b: '43', c: {}};
# -> ], }, ), ]; }; );  +; -; (+) (-) (*) (/) ++); --); ++]); --]); (" "); [" "]; {" "}; &( (& += -= *=  /=
#mlt raw " i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i); i++); i++); i++); ++i); ++i); ++i);"

# mlt raw " i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i); i--); i--); i--); --i); --i); --i);"

# "+p     vbUea   {`r}`n``e[>ko   10jk``e-e>

##----- r2( r3) r4;
# mlt raw " get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();get(); get();get();get();get();get();get();get();get();get();get();get();get();get();get();get();"

##----- 花阔号换行 输入 r3{ r5`r`n r4}  l4<ctrl>+r3[  r2k r3o
#mlt raw "{`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko"
# mlt raw "{`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko {`r}`n``eko"
# mlt raw "int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; int a, b, c, d, e, f; " 

#------ insert态 上一行输入 <esc>ko   
# mlt raw ";jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko ;jkko "
#------ insert态 下一行输入 <esc>o
# mlt raw ";jko ;jko ;jko ;jko ;jko ;jko ;jko ;jko ;jko ;jko ;jko ;jko ;jko ;jko ;jko ;jko ;jko ;jko ;jko ;jko ;jko "
#------ insert态 下下行输入 <esc>jo
# mlt raw ";jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo ;jkjo "

#------ insert态 上跳空行
# mlt raw ";jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko ;jk{ko "
#------ insert态 下跳空行
# mlt raw ";jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o ;jk}o "

#------ insert态 下2级括号 插入
# mlt raw ";jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko ;jk2[{ko "
#------ insert态 上2级括号 插入
# mlt raw ";jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o ;jk2]}o "

#------选中block    
# mlt raw ";jkva{Vy ;jkva{Vy ;jkva{Vy ;jkva{Vy ;jkva{Vy ;jkva{Vy ;jkva{Vy ;jkva{Vy ;jkva{Vy ;jkva{Vy ;jkva{Vy ;jkva{Vy ;jkva{Vy ;jkva{Vy ;jkva{Vy ;jkva{Vy "
# mlt raw ";jkva{Voky ;jkva{Voky ;jkva{Voky ;jkva{Voky ;jkva{Voky ;jkva{Voky ;jkva{Voky ;jkva{Voky ;jkva{Voky ;jkva{Voky ;jkva{Voky ;jkva{Voky ;jkva{Voky ;jkva{Voky ;jkva{Voky ;jkva{Voky "
# mlt raw ";jkva{a{Vy ;jkva{a{Vy ;jkva{a{Vy ;jkva{a{Vy ;jkva{a{Vy ;jkva{a{Vy ;jkva{a{Vy ;jkva{a{Vy ;jkva{a{Vy ;jkva{a{Vy ;jkva{a{Vy ;jkva{a{Vy ;jkva{a{Vy ;jkva{a{Vy ;jkva{a{Vy ;jkva{a{Vy "

#------选中2层block  花括号单行模式
# mlt raw ";jkva{a{okd ;jkva{a{okd ;jkva{a{okd ;jkva{a{okd ;jkva{a{okd ;jkva{a{okd ;jkva{a{okd ;jkva{a{okd ;jkva{a{okd ;jkva{a{okd ;jkva{a{okd ;jkva{a{okd ;jkva{a{okd ;jkva{a{okd ;jkva{a{okd ;jkva{a{okd "
# mlt raw ";jkva{a{oky ;jkva{a{oky ;jkva{a{oky ;jkva{a{oky ;jkva{a{oky ;jkva{a{oky ;jkva{a{oky ;jkva{a{oky ;jkva{a{oky ;jkva{a{oky ;jkva{a{oky ;jkva{a{oky ;jkva{a{oky ;jkva{a{oky ;jkva{a{oky ;jkva{a{oky "

#------选中函数
#------ r4] r3[ <leftshift>v l3% l2y r3d -------选中函数yd
# mlt raw ";jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky ;jk][V%ky "
# mlt raw "p=`] p=`] p=`] p=`] p=`] p=`] p=`] p=`] p=`] p=`] p=`] p=`] p=`] p=`] p=`] p=`] p=`] p=`] p=`] p=`] p=`] "


##-----           i++); >>``r2i r4+ r3) r4;``                 ++i); >> `` r4+ r2i r3) r4; ``
# mlt raw " i++); i++);++i); i--);--i); i++);++i); i--);--i); i++);++i); i--);--i); i++);++i); i--);--i); i++);++i); i--);--i); i++);++i); i--);--i); i++);++i); i--);--i); i++);++i); i++); i++); i++);++i); i--);--i); i++);++i); i--);--i); i++);++i); i--);--i); i++);++i); i--);--i); i++);++i); i--);--i); i++);++i); i--);--i); i++);++i); i++);"
# mlt raw " j++); j++);++j); j--);--j); j++);++j); j--);--j); j++);++j); j--);--j); j++);++j); j--);--j); j++);++j); j--);--j); j++);++j); j--);--j); j++);++j); j++); j++); j++);++j); j--);--j); j++);++j); j--);--j); j++);++j); j--);--j); j++);++j); j--);--j); j++);++j); j--);--j); j++);++j); j--);--j); j++);++j); j++);"

##-----           i++); >>``r3p r4+ r3) r4;``                 ++i); >> `` r4+ r2i r3) r4; ``
# mlt raw " p++); p++);++p); p--);--p); p++);++p); p--);--p); p++);++p); p--);--p); p++);++p); p--);--p); p++);++p); p--);--p); p++);++p); p--);--p); p++);++p); p++); p++); p++);++p); p--);--p); p++);++p); p--);--p); p++);++p); p--);--p); p++);++p); p--);--p); p++);++p); p--);--p); p++);++p); p--);--p); p++);++p); p++);"

# mlt raw "for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko for (int i = 0; i < 100; ++i) {`r}`n``eko {`r}`n``eko"
# mlt raw "for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko for (int i = 0; i < 100; i--) {`r}`n``eko {`r}`n``eko"
# mlt raw "for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko for (jnt j = 0; j < 100; j++) {`r}`n``eko {`r}`n``eko"
# mlt raw "for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko for (jnt j = 0; j < 100; --j) {`r}`n``eko {`r}`n``eko"


##----- r2( r4" l2%  r4"  r2, r2& r3) r4;
# mlt raw 'scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); scanf("%d", &x); '

##----- r2( r4"  r5`\ r4" r3) r4;
# mlt raw 'printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); printf("yes.`n"); '
# mlt raw 'printf("%s %ld %3.2f %p yes.`n", str, count); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); printf("%s %ld %3.2f %p yes.`n, str, cnt); '

##----- r3= r4' r3;
# mlt raw "ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; ch = 'A'; "

# mlt raw "{'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; {'A', 'B', 'C'}; "
# mlt raw "{9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; {9, 8, 7, 6, 5, 0}; "
#bubble sort
# mlt raw "for (int i=0; i<n && swap; i++) swap = false; for (int j=0; j<n-1-i; j--) if (a[j] > a[j+1]) swap = true; int t=a[j]; a[j]=a[j+1]; a[j+1]=t; for (int i=0; i<n && swap; i++) swap = false; for (int j=0; j<n-1-i; j--) if (a[j] > a[j+1]) swap = true; int t=a[j]; a[j]=a[j+1]; a[j+1]=t; for (int i=0; i<n && swap; i++) swap = false; for (int j=0; j<n-1-i; j--) if (a[j] > a[j+1]) swap = true; int t=a[j]; a[j]=a[j+1]; a[j+1]=t; for (int i=0; i<n && swap; i++) swap = false; for (int j=0; j<n-1-i; j--) if (a[j] > a[j+1]) swap = true; int t=a[j]; a[j]=a[j+1]; a[j+1]=t; for (int i=0; i<n && swap; i++) swap = false; for (int j=0; j<n-1-i; j--) if (a[j] > a[j+1]) swap = true; int t=a[j]; a[j]=a[j+1]; a[j+1]=t; for (int i=0; i<n && swap; i++) swap = false; for (int j=0; j<n-1-i; j--) if (a[j] > a[j+1]) swap = true; int t=a[j]; a[j]=a[j+1]; a[j+1]=t; for (int i=0; i<n && swap; i++) swap = false; for (int j=0; j<n-1-i; j--) if (a[j] > a[j+1]) swap = true; int t=a[j]; a[j]=a[j+1]; a[j+1]=t; for (int i=0; i<n && swap; i++) swap = false; for (int j=0; j<n-1-i; j--) if (a[j] > a[j+1]) swap = true; int t=a[j]; a[j]=a[j+1]; a[j+1]=t; for (int i=0; i<n && swap; i++) swap = false; for (int j=0; j<n-1-i; j--) if (a[j] > a[j+1]) swap = true; int t=a[j]; a[j]=a[j+1]; a[j+1]=t; for (int i=0; i<n && swap; i++) swap = false; for (int j=0; j<n-1-i; j--) if (a[j] > a[j+1]) swap = true; int t=a[j]; a[j]=a[j+1]; a[j+1]=t; for (int i=0; i<n && swap; i++) swap = false; for (int j=0; j<n-1-i; j--) if (a[j] > a[j+1]) swap = true; int t=a[j]; a[j]=a[j+1]; a[j+1]=t; "
#insert sort
# mlt raw "for (int i=0; i<n; i++) int t=a[i]; int j=i-1; while (j>=0 && a[j]>t) a[j+1]=a[j]; jkjo a[j+1]=t; for (int i=0; i<n; i++) int t=a[i]; int j=i-1; while (j>=0 && a[j]>t) a[j+1]=a[j]; jkjo a[j+1]=t; for (int i=0; i<n; i++) int t=a[i]; int j=i-1; while (j>=0 && a[j]>t) a[j+1]=a[j]; jkjo a[j+1]=t; for (int i=0; i<n; i++) int t=a[i]; int j=i-1; while (j>=0 && a[j]>t) a[j+1]=a[j]; jkjo a[j+1]=t; for (int i=0; i<n; i++) int t=a[i]; int j=i-1; while (j>=0 && a[j]>t) a[j+1]=a[j]; jkjo a[j+1]=t; for (int i=0; i<n; i++) int t=a[i]; int j=i-1; while (j>=0 && a[j]>t) a[j+1]=a[j]; jkjo a[j+1]=t; for (int i=0; i<n; i++) int t=a[i]; int j=i-1; while (j>=0 && a[j]>t) a[j+1]=a[j]; jkjo a[j+1]=t; for (int i=0; i<n; i++) int t=a[i]; int j=i-1; while (j>=0 && a[j]>t) a[j+1]=a[j]; jkjo a[j+1]=t; for (int i=0; i<n; i++) int t=a[i]; int j=i-1; while (j>=0 && a[j]>t) a[j+1]=a[j]; jkjo a[j+1]=t; for (int i=0; i<n; i++) int t=a[i]; int j=i-1; while (j>=0 && a[j]>t) a[j+1]=a[j]; jkjo a[j+1]=t; for (int i=0; i<n; i++) int t=a[i]; int j=i-1; while (j>=0 && a[j]>t) a[j+1]=a[j]; jkjo a[j+1]=t; "
#select sort
# mlt raw "for (int i=0; i<n; i++) int m=i; for (int j=i+1; j<n; j++) if (a[j] < m) m = j; int t = a[i]; a[i] = a[m], a[m] = t; for (int i=0; i<n; i++) int m=i; for (int j=i+1; j<n; j++) if (a[j] < m) m = j; int t = a[i]; a[i] = a[m], a[m] = t; for (int i=0; i<n; i++) int m=i; for (int j=i+1; j<n; j++) if (a[j] < m) m = j; int t = a[i]; a[i] = a[m], a[m] = t; for (int i=0; i<n; i++) int m=i; for (int j=i+1; j<n; j++) if (a[j] < m) m = j; int t = a[i]; a[i] = a[m], a[m] = t; for (int i=0; i<n; i++) int m=i; for (int j=i+1; j<n; j++) if (a[j] < m) m = j; int t = a[i]; a[i] = a[m], a[m] = t; for (int i=0; i<n; i++) int m=i; for (int j=i+1; j<n; j++) if (a[j] < m) m = j; int t = a[i]; a[i] = a[m], a[m] = t; for (int i=0; i<n; i++) int m=i; for (int j=i+1; j<n; j++) if (a[j] < m) m = j; int t = a[i]; a[i] = a[m], a[m] = t; for (int i=0; i<n; i++) int m=i; for (int j=i+1; j<n; j++) if (a[j] < m) m = j; int t = a[i]; a[i] = a[m], a[m] = t; for (int i=0; i<n; i++) int m=i; for (int j=i+1; j<n; j++) if (a[j] < m) m = j; int t = a[i]; a[i] = a[m], a[m] = t; for (int i=0; i<n; i++) int m=i; for (int j=i+1; j<n; j++) if (a[j] < m) m = j; int t = a[i]; a[i] = a[m], a[m] = t; for (int i=0; i<n; i++) int m=i; for (int j=i+1; j<n; j++) if (a[j] < m) m = j; int t = a[i]; a[i] = a[m], a[m] = t; "

#---------shell sort
# mlt raw "for(int gap=n/2; gap>0; gap/=2) for(int j=gap; j<n; j++) for(k=j-gap; k>=0 && a[k]>a[k+gap]; k-=gap) int t=a[k+gap]; a[k+gap]=a[k]; a[k]=t; for(int gap=n/2; gap>0; gap/=2) for(int j=gap; j<n; j++) for(k=j-gap; k>=0 && a[k]>a[k+gap]; k-=gap) int t=a[k+gap]; a[k+gap]=a[k]; a[k]=t; for(int gap=n/2; gap>0; gap/=2) for(int j=gap; j<n; j++) for(k=j-gap; k>=0 && a[k]>a[k+gap]; k-=gap) int t=a[k+gap]; a[k+gap]=a[k]; a[k]=t; for(int gap=n/2; gap>0; gap/=2) for(int j=gap; j<n; j++) for(k=j-gap; k>=0 && a[k]>a[k+gap]; k-=gap) int t=a[k+gap]; a[k+gap]=a[k]; a[k]=t; for(int gap=n/2; gap>0; gap/=2) for(int j=gap; j<n; j++) for(k=j-gap; k>=0 && a[k]>a[k+gap]; k-=gap) int t=a[k+gap]; a[k+gap]=a[k]; a[k]=t; for(int gap=n/2; gap>0; gap/=2) for(int j=gap; j<n; j++) for(k=j-gap; k>=0 && a[k]>a[k+gap]; k-=gap) int t=a[k+gap]; a[k+gap]=a[k]; a[k]=t; for(int gap=n/2; gap>0; gap/=2) for(int j=gap; j<n; j++) for(k=j-gap; k>=0 && a[k]>a[k+gap]; k-=gap) int t=a[k+gap]; a[k+gap]=a[k]; a[k]=t; for(int gap=n/2; gap>0; gap/=2) for(int j=gap; j<n; j++) for(k=j-gap; k>=0 && a[k]>a[k+gap]; k-=gap) int t=a[k+gap]; a[k+gap]=a[k]; a[k]=t
