set nocompatible 
filetype plugin on

call plug#begin()
	Plug 'tpope/vim-commentary'
"	Plug 'Exafunction/windsurf.vim'
	Plug 'github/copilot.vim'
	Plug 'lifepillar/vim-solarized8'
call plug#end()

set nu ru ts=4 sw=4 autoindent cindent smartindent noswapfile undofile autoread
syntax on
set autochdir
set undodir="~/.vim/undodir"
set undofile
set undolevels =1000
set undoreload =10000
set fileencoding=utf-8
set bs=indent,eol,start

set termguicolors
set background=dark
colo solarized8


let mapleader = " "
inoremap jk <esc>
nnoremap <c-j> 5j
nnoremap <c-k> 5k
nnoremap <c-h> ^
nnoremap <c-l> $
nnoremap <leader>w :w! <cr>
nnoremap <leader>rc :e ~/_vimrc <cr>
"nnoremap <leader>rs :so ~/vimrc <cr>
nnoremap <leader>yf :let @+=expand("%:.") <cr>

let g:copilot_enabled = 0
nnoremap <F12> :Copilot enable<CR>
nnoremap <c-F12> :Copilot disable<CR>

func! Winshow()
	let nno = expand("%:r") . ".out"
	let nni = expand("%:r") . ".in"
	if  bufexists(nno)
		exec "bw! " . nno
		exec "bw! " . nni
	else
		exec "new " . nno
		exec "vnew " . nni
		exec "resize 10"
	endif
endfunc

set shell=cmd.exe
set shellcmdflag=/c

set makeprg=g++\ -std=c++17\ -g\ -Wall\ -Wextra\ %\ -o\ %<.exe
nmap <silent> <F9> :w<CR>:make<CR>:cw<cr>:!%<.exe<cr>

nnoremap <F8> :call Winshow()<CR>

" =========================
" F4：Termdebug（Windows 可用）
" =========================
packadd termdebug
let g:termdebug_wide = 10
nnoremap <F4> :Termdebug %<.exe<CR>

" =========================
" F2：Windows 下创建副本（代替 ln -s）
" =========================
nnoremap <F2> :silent execute '!copy /Y "' . expand('%') . '" a.cpp'<CR>

"au BufNewFile *.cpp 0r ~/noi/coding/config/skeleton.c | %s/xxx/\=expand("%:r")/g
au BufNewFile *.cpp 0r ~/noi/coding/config/skeleton_full.c | %s/xxx/\=expand("%:r")/g
au FileType cpp set keywordprg=cppman
"#!/bin/bash
"ulimit -s unlimited
"setxkbmap -option ctrl:swapcaps
"setxkbmap -option
"chmod +x dp.sh
"colo molokai


